name: Test

on:
  push:
    branches:
    - main
    
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
